### ISSUE TITLE
released

### ISSUE THREAD

**Issue by sorrowyn** [Yejin0111/ADD-GCN#1]
Hello, when can the source code be released

**Comment by Yejin0111** [comment]
I will release the source code as soon as possible.

**Comment by Yejin0111** [comment]
> Hello, when can the source code be released

I will release the source code as soon as possible.

**Comment by sorrowyn** [comment]
Thanks! I noticed that many coders do not provide CAM code. Will the visualization code be released this time?

**Comment by WangHelin1997** [comment]
+1, when can the source code be released

**Comment by Yejin0111** [comment]
> Thanks! I noticed that many coders do not provide CAM code. Will the visualization code be released this time?

For CAM, you can find the original code from 'https://github.com/zhoubolei/CAM/blob/master/pytorch_CAM.py'. It's easy to re-implement.

**Comment by Yejin0111** [comment]
> +1, when can the source code be released

Maybe 1-2 weeks later.

**Comment by sorrowyn** [comment]
> 
> 
> > Thanks! I noticed that many coders do not provide CAM code. Will the visualization code be released this time?
> 
> For CAM, you can find the original code from 'https://github.com/zhoubolei/CAM/blob/master/pytorch_CAM.py'. It's easy to re-implement.

Thank ！Thank ！

**Comment by sorrowyn** [comment]
In the paper, some of SAM's details are still unclear.
I don't know the D' channel and the pool parameter
