### ISSUE TITLE
Question about the ADD-GCN network

### ISSUE THREAD

**Issue by seven-sent** [Yejin0111/ADD-GCN#12]
Hello. Thank you for sharing your excellent work!
Since I am new in computer vision and deep learning, I have some doubts about the codes.

https://github.com/Yejin0111/ADD-GCN/blob/b7653fe697a870826debcca4d23203c4e37e7d86/models/add_gcn.py#L137

I wonder why the final z  is added to v?

Another question is:
Is it feasible if I want to apply this method to regression problems?
Or can you provide some ideas about it?

Looking forward to your response.

**Comment by Yejin0111** [comment]
Q1: z = v + z?
It is the residual operation that refers to  ResNet. You can get more explanations in [ResNet](https://arxiv.org/abs/1512.03385).

Q2: How to use the code in regression problems?
I think a simple way to fit the regression problems is using [data binning](https://en.wikipedia.org/wiki/Data_binning). For example, if you want to regress a value in the range of 0 to 1, you can group your continuous outputs into a smaller number of "bins". It transfers your regression problem to a classification problem. Then you can directly use the ADD-GCN to solve your problem.

**Comment by seven-sent** [comment]
Thanks for your reply!
I may try your suggestions later.

Thanks again~
