### ISSUE TITLE
Turn cudnn.deterministic to False lead to faster and better trainning

### ISSUE THREAD

**Issue by thuangb** [Yejin0111/ADD-GCN#13]
Hi, thank for this great work. What I have found is that turn cudnn.deterministic to False in line 49 of file main.py make the training way more faster and sometimes leads to better accuracy of the final model. I experience this phenomena with COCO, VOC and even my private dataset. Do you think this is a bug or something ?

**Comment by Yejin0111** [comment]
No, the "cudnn.deterministic" switch is used to repeat the result of your experiments. You can search for more information about this.

**Comment by thuangb** [comment]
So you only use cudnn.deterministic only for experiments and inference things and turn it off when training? Is that correct ?

**Comment by Yejin0111** [comment]
No, "make the experiment reproducible" means you can train the same model when you turn on this switch in the TRAINING stage.

**Comment by thuangb** [comment]
Ah OK that's make sense. Thank you. So I'm close this issue now
