### ISSUE TITLE
About code references

### ISSUE THREAD

**Issue by seven-sent** [Yejin0111/ADD-GCN#14]
As I don't see your license on github, can I quote and modify parts of your code in my own project?

My project is related to the face task. I would like to introduce the attention part and the GCN part into my method.
If allowed, I will state the reference in the code.

Looking forward to your reply.

**Comment by Yejin0111** [comment]
Sure, you can.

**Comment by Yejin0111** [comment]
Sure, you can.

**Comment by seven-sent** [comment]
Thank you so much!
