### ISSUE TITLE
pretrained weigths 

### ISSUE THREAD

**Issue by abhigoku10** [Yejin0111/ADD-GCN#16]
@Yejin0111  can you please share your pretrained models on google drive or onedrive ? it would be helpful
Thanks in advance

**Comment by Yejin0111** [comment]
I put COCO pretrained weights on this link: https://drive.google.com/file/d/12NkyiQlxBjKFPdCn1WV9CzETHDkEvgn3/view?usp=sharing

**Comment by abhigoku10** [comment]
@Yejin0111  thanks a lot !!
