### ISSUE TITLE
Training for  COCO2014

### ISSUE THREAD

**Issue by JiaweiZhao-git** [Yejin0111/ADD-GCN#3]
Could you please share your training command? Thanks!

**Comment by Yejin0111** [comment]
> Could you please share your training command? Thanks!

`python main.py --data COCO2014 --data_root_dir {YOUR-ROOT-DATA-DIR} --model_name ADD_GCN --save_dir {YOUR-SAVE-MODEL-DIR} -b {BATCH-SIZE} --lr {LEARNING-RATE}`

For 2GPUs:
{BATCH-SIZE}: In my set up, I always put 16 or 18 in each GPU.
{LEARNING-RATE}: I used to get good results with LR in {0.04\~0.05}.
