### ISSUE TITLE
Image-size and batch-size

### ISSUE THREAD

**Issue by sorrowyn** [Yejin0111/ADD-GCN#4]
In voc2007, when Image-size is 576x576 and batch size of each GPU is 18(16), but the out of memory is printed. 4*2080Ti, 11G.

Your memory of GPU?

**Comment by Yejin0111** [comment]
> In voc2007, when Image-size is 576x576 and batch size of each GPU is 18(16), but the out of memory is printed. 4*2080Ti, 11G.
> 
> Your memory of GPU?

The training setup of 16 batch-size of each GPU only works in 448x448 image-size.

**Comment by sorrowyn** [comment]
> 
> 
> > In voc2007, when Image-size is 576x576 and batch size of each GPU is 18(16), but the out of memory is printed. 4*2080Ti, 11G.
> > Your memory of GPU?
> 
> The training setup of 16 batch-size of each GPU only works in 448x448 image-size.

Thank you, senior.
'''
transforms.Resize((args.image_size+64, args.image_size+64)), # is this a mistake?? in ADD-GCN/data/__init__.py  #L104
https://github.com/Yejin0111/ADD-GCN/blob/b7653fe697a870826debcca4d23203c4e37e7d86/data/__init__.py#L104
'''
And I have a question:
File "/data/mll/MLIC/ADD-GCN/util.py", line 152, in average_precision
    precision_at_i /= pos_count
ZeroDivisionError: float division by zero
======>
When i try in voc2012, some errors have occurred
<======

**Comment by Yejin0111** [comment]
> > > In voc2007, when Image-size is 576x576 and batch size of each GPU is 18(16), but the out of memory is printed. 4*2080Ti, 11G.
> > > Your memory of GPU?
> > 
> > 
> > The training setup of 16 batch-size of each GPU only works in 448x448 image-size.
> 
> Thank you, senior.
> '''
> transforms.Resize((args.image_size+64, args.image_size+64)), # is this a mistake?? in ADD-GCN/data/**init**.py #L104
> https://github.com/Yejin0111/ADD-GCN/blob/b7653fe697a870826debcca4d23203c4e37e7d86/data/__init__.py#L104
> 
> 
> '''
> And I have a question:
> File "/data/mll/MLIC/ADD-GCN/util.py", line 152, in average_precision
> precision_at_i /= pos_count
> ZeroDivisionError: float division by zero
> ======>
> When i try in voc2012, some errors have occurred
> <======

1. 
```
transforms.Resize((args.image_size+64, args.image_size+64)), # is this a mistake?? in ADD-GCN/data/init.py #L104
```
This is not a mistake. I random crop a region within a larger image for training. That's why I firstly resize the input image to "input_size + 64". 


2. You can not evaluate voc2012 test set in the training phase, because we do not have the test set labels. You should predict all outputs and submit them to the official website for evaluation.

**Comment by sorrowyn** [comment]
> 
> 
> > > > In voc2007, when Image-size is 576x576 and batch size of each GPU is 18(16), but the out of memory is printed. 4*2080Ti, 11G.
> > > > Your memory of GPU?
> > > 
> > > 
> > > The training setup of 16 batch-size of each GPU only works in 448x448 image-size.
> > 
> > 
> > Thank you, senior.
> > '''
> > transforms.Resize((args.image_size+64, args.image_size+64)), # is this a mistake?? in ADD-GCN/data/**init**.py #L104
> > https://github.com/Yejin0111/ADD-GCN/blob/b7653fe697a870826debcca4d23203c4e37e7d86/data/__init__.py#L104
> > 
> > '''
> > And I have a question:
> > File "/data/mll/MLIC/ADD-GCN/util.py", line 152, in average_precision
> > precision_at_i /= pos_count
> > ZeroDivisionError: float division by zero
> > ======>
> > When i try in voc2012, some errors have occurred
> > <======
> 
> 
> ```
> transforms.Resize((args.image_size+64, args.image_size+64)), # is this a mistake?? in ADD-GCN/data/init.py #L104
> ```
> 
> This is not a mistake. I random crop a region within a larger image for training. That's why I firstly resize the input image to "input_size + 64".
> 
>     1. You can not evaluate voc2012 test set in the training phase, because we do not have the test set labels. You should predict all outputs and submit them to the official website for evaluation.
Thank you for your advice, which helped me to understand the problem.
now I understand.
Thank you, senior.
