### ISSUE TITLE
issue about s_m & s_r 

### ISSUE THREAD

**Issue by realyao** [Yejin0111/ADD-GCN#8]
Hi, thanks for your excellent work.

I noticed you wrote  in your paper and code,"we simply average s_m and s_r to produce the final scores s".
then I experimented with only s_m as the final score, and the result mAP were similar or even higher.

Does this mean that GCN played little role in this work？

**Comment by Yejin0111** [comment]
Hi, I just tested what you said. The mAP is only 4% when only output s<sub>m as the final score. Could you tell me how you get the result? Thanks.

**Comment by Yejin0111** [comment]
Hi, I just tested what you said. The mAP is only 4% when only output s<sub>m</sub> as the final score. Could you tell me how you get the result? Thanks.

**Comment by sorrowyn** [comment]
only output ![1](http://latex.codecogs.com/svg.latex?\{s_m}) as the final score
![图片](https://user-images.githubusercontent.com/19569162/114342434-6c536c80-9b8e-11eb-8b2d-a50ab1520c6e.png)
![图片](https://user-images.githubusercontent.com/19569162/114342497-842af080-9b8e-11eb-9c7d-e1effdf3702b.png)

**Comment by sorrowyn** [comment]
only output ![1](http://latex.codecogs.com/svg.latex?\{s_r}) as the final score
![图片](https://user-images.githubusercontent.com/19569162/114343353-44650880-9b90-11eb-9d30-e189bd09f928.png)
![图片](https://user-images.githubusercontent.com/19569162/114343367-4d55da00-9b90-11eb-819c-c9768879d633.png)

**Comment by sorrowyn** [comment]
> 
> 
> Hi, I just tested what you said. The mAP is only 4% when only output sm as the final score. Could you tell me how you get the result? Thanks.
the ![1](http://latex.codecogs.com/svg.latex?s_r) is more important than the ![2](http://latex.codecogs.com/svg.latex?s_m)

**Comment by realyao** [comment]
是的，就和 @sorrowyn 一样，我在 `trainer.py` 中修改为 `outputs = 2 * outputs1`，得到类似的结果。

我还是个刚入门的新手，这样修改是不是把问题想太简单了🤣

**Comment by Yejin0111** [comment]
> 是的，就和 @sorrowyn 一样，我在 `trainer.py` 中修改为 `outputs = 2 * outputs1`，得到类似的结果。
> 
> 我还是个刚入门的新手，这样修改是不是把问题想太简单了🤣

你好，你说修改为`outputs = 2 * outputs1`之后得到类似的结果，我刚才试了一下，mAP只有70.4%，根据 @sorrowyn 的贴图结果，只使用output1（s<sub>m</sub>）作为输出mAP也只有63.1%，而使用平均的话，mAP有84%。

**Comment by realyao** [comment]
我发现 应该是我只用了很小一部分数据集实验，得到了有偏差的结果。

感谢解答，抱歉打扰  : )
